export const formatCurrency = (value) => `${Number(value).toLocaleString("pt-PT")} Kz`;

export const PROPERTIES = [
  {
    id: 1,
    name: "Baía Resort Premium",
    location: "Cabo Ledo",
    price: 620,
    rating: 9.2,
    reviews: 120,
    discount: 10,
    description: "Vista mar, ideal para casais e famílias.",
    image: "./img/imagens_gerentes/resorts/fabio-fistarol-qai_Clhyq0s-unsplash.jpg",
    breakfast: true,
    refundable: false,
    available: true,
    payLater: true,
    amenities: ["wifi", "pool", "parking", "restaurant", "vip"],
    mealPlans: ["breakfast"],
    recommendedScore: 94,
  },
  {
    id: 2,
    name: "Ocean View Lodge",
    location: "Ilha do Mussulo",
    price: 840,
    rating: 9.5,
    reviews: 74,
    discount: 23,
    description: "Suites com varanda e serviço premium.",
    image: "./img/imagens_seccoes/bilderboken-rlwE8f8anOc-unsplash.jpg",
    breakfast: true,
    refundable: true,
    available: true,
    payLater: false,
    amenities: ["wifi", "pool", "ac", "restaurant", "gym"],
    mealPlans: ["breakfast", "all-inclusive"],
    recommendedScore: 98,
  },
  {
    id: 3,
    name: "Mupas Beach & Spa",
    location: "Cabo Ledo",
    price: 710,
    rating: 8.9,
    reviews: 88,
    discount: 15,
    description: "Conforto moderno com acesso direto à praia.",
    image: "./img/imagens_seccoes/pexels-ketut-subiyanto-4907441.jpg",
    breakfast: true,
    refundable: true,
    available: true,
    payLater: true,
    amenities: ["wifi", "pool", "spa", "parking", "kitchen"],
    mealPlans: ["breakfast", "lunch-dinner"],
    recommendedScore: 92,
  },
  {
    id: 4,
    name: "Sunset Eco Villas",
    location: "Luanda",
    price: 540,
    rating: 8.4,
    reviews: 58,
    discount: 0,
    description: "Ambiente natural, ideal para descanso.",
    image: "./img/imagens_seccoes/webfactory-ltd-B0tAwAQUbzA-unsplash.jpg",
    breakfast: false,
    refundable: true,
    available: false,
    payLater: true,
    amenities: ["wifi", "parking", "kitchen"],
    mealPlans: [],
    recommendedScore: 83,
  },
  {
    id: 5,
    name: "Palm Horizon Hotel",
    location: "Cabo Ledo",
    price: 930,
    rating: 9.0,
    reviews: 63,
    discount: 10,
    description: "Perfeito para férias completas all-inclusive.",
    image: "./img/imagens_seccoes/isidore-decamon-FUQrshH4Grc-unsplash.jpg",
    breakfast: true,
    refundable: false,
    available: true,
    payLater: false,
    amenities: ["wifi", "pool", "restaurant", "gym", "ac"],
    mealPlans: ["all-inclusive"],
    recommendedScore: 91,
  },
  {
    id: 6,
    name: "Costa Azul Residence",
    location: "Mussulo",
    price: 470,
    rating: 8.8,
    reviews: 36,
    discount: 8,
    description: "Ótimo custo-benefício com ambientes amplos.",
    image: "./img/galeria/pexels-asadphoto-3601426.jpg",
    breakfast: false,
    refundable: true,
    available: true,
    payLater: true,
    amenities: ["wifi", "parking", "ac", "kitchen"],
    mealPlans: ["lunch-dinner"],
    recommendedScore: 88,
  },
  {
    id: 7,
    name: "Tropical Infinity Suites",
    location: "Cabo Ledo",
    price: 990,
    rating: 9.8,
    reviews: 20,
    discount: 10,
    description: "Suites de luxo com vista panorâmica.",
    image: "./img/galeria/pexels-pixabay-274249.jpg",
    breakfast: true,
    refundable: false,
    available: true,
    payLater: false,
    amenities: ["wifi", "pool", "vip", "gym", "restaurant"],
    mealPlans: ["breakfast", "all-inclusive"],
    recommendedScore: 99,
  },
  {
    id: 8,
    name: "Retiro Maré Mansa",
    location: "Luanda",
    price: 390,
    rating: 8.1,
    reviews: 41,
    discount: 0,
    description: "Estadia tranquila com foco em relaxamento.",
    image: "./img/galeria/pexels-pixabay-261169.jpg",
    breakfast: true,
    refundable: true,
    available: true,
    payLater: true,
    amenities: ["wifi", "pool"],
    mealPlans: ["breakfast"],
    recommendedScore: 79,
  },
];
